# Generated by Django 2.1.15 on 2021-02-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='UserEmail',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='UserFirstName',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='UserLastName',
        ),
        migrations.RemoveField(
            model_name='userlist',
            name='UserMiddleName',
        ),
    ]
