# Generated by Django 3.0.10 on 2021-02-12 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiclist',
            name='CloseBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topic_Closed_By', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topiclist',
            name='CloseDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='topiclist',
            name='IsClose',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topiclist',
            name='SMSText',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='topiclist',
            name='WhatsAppText',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
