# Generated by Django 3.0.10 on 2021-02-27 21:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='ContactCell',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=100, null=True, region=None),
        ),
    ]
