# Generated by Django 3.0.10 on 2021-02-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='UserEmail',
        ),
        migrations.AlterField(
            model_name='userlist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='UserType',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Professional', 'Professional')], default='Customer', max_length=15),
        ),
    ]
