# Generated by Django 3.0.10 on 2021-02-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiclist',
            name='SubCategory',
        ),
        migrations.AlterField(
            model_name='reviewlist',
            name='UpdatedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='TopicSubCats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.TopicList')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SubCategoryList')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryInCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CategoryList')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.CityList')),
            ],
        ),
    ]
