# Generated by Django 3.0.10 on 2021-02-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='UpdatedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategorylist',
            name='UpdatedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
