# Generated by Django 2.1.15 on 2021-02-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210210_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppliationList',
            new_name='ApplciationList',
        ),
    ]
