# Generated by Django 3.0.10 on 2021-02-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210212_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiclist',
            name='UpdatedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
