# Generated by Django 3.0.10 on 2021-02-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210210_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AppliationList'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='ContactCell',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='UserMiddleName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
