# Generated by Django 3.0.10 on 2021-02-27 21:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210228_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='ContactCell',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
