# Generated by Django 3.0.10 on 2021-02-13 15:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_topiclist_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsdetaillist',
            name='FileName',
            field=models.FileField(default=1, upload_to=accounts.models.get_upload_path),
            preserve_default=False,
        ),
    ]
