# Generated by Django 3.0.10 on 2021-02-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210214_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='City',
        ),
    ]
