# Generated by Django 3.0.10 on 2021-02-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_categoryincity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiclist',
            name='SubCategory',
        ),
        migrations.CreateModel(
            name='TopicSubCats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.TopicList')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SubCategoryList')),
            ],
        ),
    ]
