# Generated by Django 3.0.10 on 2021-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userlist_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='City',
            field=models.CharField(max_length=30),
        ),
    ]
