# Generated by Django 3.0.10 on 2021-02-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210218_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicdetaillist',
            name='AssetsDetail',
        ),
        migrations.RemoveField(
            model_name='topicdetaillist',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='topicdetaillist',
            name='City',
        ),
        migrations.RemoveField(
            model_name='topicdetaillist',
            name='SubCategory',
        ),
    ]
