# Generated by Django 3.0.10 on 2021-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210219_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicdetaillist',
            name='Selected',
            field=models.BooleanField(default=False),
        ),
    ]
