# Generated by Django 3.0.10 on 2021-02-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_topicdetaillist_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Otp', models.CharField(max_length=10)),
                ('expire_minute', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('doc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
