# Generated by Django 3.1.5 on 2021-02-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_user_is_professional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_professional',
        ),
    ]
