# Generated by Django 3.1.5 on 2021-02-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_user_is_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Professional', 'Professional')], default='Customer', max_length=15),
        ),
    ]
